name: "Airplay 2 for Home Assistant - wise_rice"
description: "Adds Airplay 2 capabilities to Home Assistant"
url: https://github.com/wise-rice/Home-Assistant-Addons/tree/main/Airplay2
version: "0.0.1.4"
slug: "airplay2"
init: false
arch:
  - aarch64
  - amd64
  - armv7
boot: "auto"
host_network: true
audio: true
options:
  airplay_name: "Hass.io"
  offset: "-0.25"
  interpolation: "auto"
  use_precision_timing: "auto"
  disable_standby_mode: "never"
  default_airplay_volume: "-24.0"
  volume_max_db: "0.0"
  high_threshold_airplay_volume: "-16.0"
  mixer_control_name: "Headphone"
  mixer_control_index: "0"
  volume_control_combined_hardware_priority: "no"
  output_backend: "pa"
  drift_tolerance_in_seconds: "0.002"
  resync_threshold_in_seconds: "0.050"
  resync_recovery_time_in_seconds: "0.100"
  audio_backend_buffer_desired_length_in_seconds: "0.35"
  output_rate: "auto"
  output_format: "auto"
  enabled: "no"
  mqtt_host: "core-mosquitto"
  mqtt_username: "user"
  mqtt_password: "password"
  mqtt_publish_cover: "no"
schema:
  airplay_name: str
  offset: str
  interpolation: str
  enabled: str
  mqtt_host: str
  mqtt_username: str
  mqtt_password: password
  mqtt_publish_cover: str
image: "wise-rice/ha-airplay2-{arch}-debian"
